[target.riscv32imc-unknown-none-elf]
rustflags = [
    "--cfg", "portable_atomic_unsafe_assume_single_core",
    "-C", "link-arg=-Tlinkall.x",
]

[unstable]
build-std = ["core", "alloc"]
build-std-features = ["compiler-builtins-mem"]
