[target.riscv32imc-unknown-none-elf]
rustflags = [
    "--cfg", "portable_atomic_unsafe_assume_single_core",
    "-C", "link-arg=-Tlinkall.x",
]

[target.thumbv6m-none-eabi]
rustflags = [
    "-C", "link-arg=--nmagic",
    "-C", "link-arg=-Tlink.x",
]
runner = "elf2uf2-rs -d"

[unstable]
build-std = ["core", "alloc"]
build-std-features = ["compiler-builtins-mem"]
